### PR TITLE
Fix regex

### PR DESCRIPTION
**Pull request by nautilebleu**
Allow to recognize URLs with an extension https://github.com/lukechilds/my-name-is-url/issues/18

### CODE REVIEW

**Comment by lukechilds** [comment]
Brilliant, thanks!

Could you add a test for this functionality to prevent regressions too?

**Comment by nautilebleu** [comment]
I added a test :)

**Comment by lukechilds** [comment]
Thanks!

Published as `my-name-is-url@1.4.0` 🎉

**Comment by nautilebleu** [comment]
Thanks 👍

**Pull request merged**
